defmodule BigBill.Search.Semantic do
  @moduledoc """
  Semantic (vector) search over bill sections, graph nodes, and analysis
  chunks using pgvector and all-MiniLM-L6-v2 embeddings.

  Embeddings are generated by the Python helper at
  `analytics/embed_query.py` and stored in the `search_embeddings` Postgres
  table (see migration `add_search_embeddings`).

  ## Examples

      # Free-text query
      BigBill.Search.Semantic.find_similar("Medicaid work requirements", limit: 10)

      # Find sections related to a known section
      BigBill.Search.Semantic.find_similar_to_section("10001", limit: 15)
  """

  require Logger

  alias BigBill.Repo

  @default_limit 20

  # Path to the Python query helper, relative to the project root.
  @embed_script "analytics/embed_query.py"

  # Python executable — override via config or env if using a venv.
  @python_bin Application.compile_env(:big_bill, [:semantic_search, :python_bin], "python3")

  # ---------------------------------------------------------------------------
  # Public API
  # ---------------------------------------------------------------------------

  @doc """
  Find the *limit* most semantically similar items to *query_text*.

  Returns a list of maps:

      %{
        source_type: "section" | "graph_node" | "analysis",
        source_id:   String.t(),
        title:       String.t() | nil,
        content:     String.t(),
        similarity:  float()   # 0.0–1.0, higher is more similar
      }

  Options:
    - `:limit` — maximum results (default #{@default_limit})
    - `:source_type` — filter to `"section"`, `"graph_node"`, or `"analysis"`
  """
  @spec find_similar(String.t(), keyword()) :: [map()]
  def find_similar(query_text, opts \\ []) when is_binary(query_text) do
    query_text = String.trim(query_text)
    if query_text == "", do: [], else: do_find_similar(query_text, opts)
  end

  @doc """
  Find items semantically similar to a bill section identified by
  *section_number*.

  Looks up the stored embedding for that section then runs a nearest-neighbor
  query, excluding the section itself from results.

  Options: same as `find_similar/2`.
  """
  @spec find_similar_to_section(String.t(), keyword()) :: [map()]
  def find_similar_to_section(section_number, opts \\ []) when is_binary(section_number) do
    case fetch_embedding("section", section_number) do
      {:ok, vec} ->
        limit = Keyword.get(opts, :limit, @default_limit)
        source_type = Keyword.get(opts, :source_type)
        query_nearest(vec, limit, source_type, exclude: {"section", section_number})

      {:error, reason} ->
        Logger.warning("Semantic: no embedding for section #{section_number}: #{reason}")
        []
    end
  end

  # ---------------------------------------------------------------------------
  # Private — embedding generation
  # ---------------------------------------------------------------------------

  defp do_find_similar(query_text, opts) do
    case embed_text(query_text) do
      {:ok, vec} ->
        limit = Keyword.get(opts, :limit, @default_limit)
        source_type = Keyword.get(opts, :source_type)
        query_nearest(vec, limit, source_type, [])

      {:error, reason} ->
        Logger.error("Semantic: embedding failed: #{reason}")
        []
    end
  end

  # Call the Python helper via System.cmd and parse its JSON output.
  defp embed_text(text) do
    script = script_path()

    case System.cmd(@python_bin, [script], input: text, stderr_to_stdout: false) do
      {output, 0} ->
        output = String.trim(output)

        case Jason.decode(output) do
          {:ok, vec} when is_list(vec) -> {:ok, vec}
          _ -> {:error, "failed to parse embedding JSON: #{inspect(output)}"}
        end

      {output, code} ->
        {:error, "embed_query.py exited #{code}: #{String.trim(output)}"}
    end
  rescue
    e -> {:error, Exception.message(e)}
  end

  # Resolve the embed_query.py path relative to the project root.
  defp script_path do
    # :code.priv_dir gives us priv/, one level below the project root
    project_root = Path.join(:code.priv_dir(:big_bill) |> to_string(), "..")
    Path.expand(Path.join(project_root, @embed_script))
  end

  # ---------------------------------------------------------------------------
  # Private — Postgres queries
  # ---------------------------------------------------------------------------

  # Look up the stored embedding vector for a known (source_type, source_id).
  defp fetch_embedding(source_type, source_id) do
    sql = """
    SELECT embedding::text
    FROM search_embeddings
    WHERE source_type = $1 AND source_id = $2
    LIMIT 1
    """

    case Repo.query(sql, [source_type, source_id]) do
      {:ok, %{rows: [[vec_text]]}} ->
        {:ok, parse_pg_vector(vec_text)}

      {:ok, %{rows: []}} ->
        {:error, "not found"}

      {:error, reason} ->
        {:error, inspect(reason)}
    end
  end

  # Run the cosine-distance nearest-neighbor search.
  defp query_nearest(vec, limit, source_type_filter, exclude_opts) do
    vec_literal = vec_to_pg_literal(vec)

    {where_clauses, params} =
      build_where_clauses(source_type_filter, exclude_opts, vec_literal)

    sql = """
    SELECT source_type, source_id, title, content,
           1 - (embedding <=> '#{vec_literal}'::vector) AS similarity
    FROM search_embeddings
    #{where_clauses}
    ORDER BY embedding <=> '#{vec_literal}'::vector
    LIMIT #{limit}
    """

    case Repo.query(sql, params) do
      {:ok, %{rows: rows}} ->
        Enum.map(rows, fn [source_type, source_id, title, content, similarity] ->
          %{
            source_type: source_type,
            source_id: source_id,
            title: title,
            content: content,
            similarity: similarity
          }
        end)

      {:error, reason} ->
        Logger.error("Semantic query failed: #{inspect(reason)}")
        []
    end
  end

  defp build_where_clauses(source_type_filter, exclude_opts, _vec_literal) do
    conditions = []
    params = []
    param_idx = 1

    {conditions, params, param_idx} =
      if source_type_filter do
        {
          conditions ++ ["source_type = $#{param_idx}"],
          params ++ [source_type_filter],
          param_idx + 1
        }
      else
        {conditions, params, param_idx}
      end

    {conditions, params, _param_idx} =
      case Keyword.get(exclude_opts, :exclude) do
        {ex_type, ex_id} ->
          {
            conditions ++
              ["NOT (source_type = $#{param_idx} AND source_id = $#{param_idx + 1})"],
            params ++ [ex_type, ex_id],
            param_idx + 2
          }

        nil ->
          {conditions, params, param_idx}
      end

    where_sql =
      if conditions == [] do
        ""
      else
        "WHERE " <> Enum.join(conditions, " AND ")
      end

    {where_sql, params}
  end

  # Convert a list of floats to a pgvector literal string, e.g. "[0.1,0.2,...]"
  defp vec_to_pg_literal(vec) when is_list(vec) do
    "[" <> Enum.map_join(vec, ",", fn v -> :erlang.float_to_binary(v / 1, [:compact, {:decimals, 8}]) end) <> "]"
  end

  # Parse a pgvector text representation like "[0.1,0.2,...]" back to a list.
  defp parse_pg_vector(text) when is_binary(text) do
    text
    |> String.trim_leading("[")
    |> String.trim_trailing("]")
    |> String.split(",")
    |> Enum.map(&String.to_float/1)
  end
end
