FROM rust:alpine AS builder

RUN apk add --no-cache musl-dev && \
    cargo install deciduous

FROM alpine:3.22

COPY --from=builder /usr/local/cargo/bin/deciduous /usr/local/bin/deciduous

WORKDIR /data

EXPOSE 3000

CMD ["deciduous", "serve", "--host", "0.0.0.0", "--port", "3000"]
